### ISSUE TITLE
gdk wayland interaction

### ISSUE THREAD

**Issue by psnszsn** [gtk-rs/gtk3-rs#101]
Is it possible to use the functions from `gdkwayland.h`?
Specifically i would like to use `gdk_wayland_window_get_wl_surface()` and `gdk_wayland_window_set_use_custom_surface()`.

**Comment by sdroege** [comment]
For GTK4 this exists now: https://github.com/gtk-rs/gtk4-rs/tree/master/gdk4-wayland

**Comment by bilelmoussaoui** [comment]
I wrote a very small part of gdk3-wayland manually for a crate I'm working on and I was wondering what would be the best way to upstream it here.

I'm thinking of adding the ffi types to gdk-sys's manual.rs & have a feature flag for enabling the gdk-wayland bindings without an extra separate crate. I only have the `gdk_wayland_window_unexport_handle` & `gdk_wayland_window_export_handle` parts, more could be added manually in the future by interested people.

**Comment by GuillaumeGomez** [comment]
Sounds like a good idea to bind them manually.

**Comment by sdroege** [comment]
This can be closed then? @GuillaumeGomez @bilelmoussaoui

**Comment by GuillaumeGomez** [comment]
No, a lot of items are still missing. I'll add them later.
