### ISSUE TITLE
Clarify bug reporting process

### ISSUE THREAD

**Issue by Susurrus** [gtk-rs/gtk3-rs#105]
I've been a little confused about where to file bugs, sometimes which gtk-rs repo to use and also when to file bugs upstream instead of in this repo. I want to make sure I'm being a good citizen and filing bugs ina  helpful matter and not just causing triage noise for this project. Therefore I think it'd be helpful if there was an official comment addressing these two things in the README for gtk. Something akin to:

Filing Bugs
--------------

Filing bugs upstream if possible ([GNOME Bugzilla](https://bugzilla.gnome.org/enter_bug.cgi)) is ideal if you believe the bug is specifically within the C libraries of GTK.

Otherwise if you believe the bug is within the Rust bindings, please file it in the appropriate repo within the gtk-rs family (glib, gio, gtk, etc.). If you are uncertain which repository to file the bug under, please file it under gtk.

**Comment by sdroege** [comment]
@GuillaumeGomez Is there anything left to be done here? You added an issue template recently but I guess that should be extended to also point to upstream gitlab?

**Comment by GuillaumeGomez** [comment]
I'm not too sure about that. It's not always obvious where to open the issue after all. The problem could come from the Rust API or not. So I'm not sure about it but you have an idea in mind, go for it!

**Comment by sdroege** [comment]
Just like what you added before for general help, something there that points to GNOME GitLab would be useful. For the cases where it's not something related to the bindings but to the C library.

**Comment by sdroege** [comment]
Should be good with the templates we have now
