### ISSUE TITLE
Add LabelExt trait implementation information for Label

### ISSUE THREAD

**Issue by silwol** [gtk-rs/gtk3-rs#111]
The LabelExt trait is currently missing from the list of implementated traits for Label in the generated documentation at http://gtk-rs.org/docs/gtk/struct.Label.html#implements

**Comment by bilelmoussaoui** [comment]
No idea where it gets the `MiscExt` trait from https://gtk-rs.org/gtk-rs/gtk/struct.Label.html#implements

**Comment by sdroege** [comment]
Well, `GtkLabel` is a subclass of `GtkMisc`, but that has no API and as such no `MiscExt` trait

**Comment by bilelmoussaoui** [comment]
> Well, `GtkLabel` is a subclass of `GtkMisc`, but that has no API and as such no `MiscExt` trait

Interesting. I guess we need to check the number of functions there's on a trait before adding it to the list of "implements"

**Comment by sdroege** [comment]
Something like that. Check how gir decides to not create a trait at all. It's probably checking for functions, signals and properties, and if any of them are actually to be generated.

**Comment by bilelmoussaoui** [comment]
I think gir isn't aware of such thing yet, as it still generates empty traits https://github.com/gtk-rs/gtk4-rs/blob/master/gtk4/src/auto/constraint_target.rs#L16-L20

**Comment by bilelmoussaoui** [comment]
Seems to be correctly generated now: https://gtk-rs.org/gtk-rs/git/docs/gtk/struct.Label.html#implements. Although it still contains the  MiscExt trait which doesn't get generated, even as en empty trait.

**Comment by sdroege** [comment]
So closeable then?

**Comment by bilelmoussaoui** [comment]
@sdroege yes and with the new docs, those broken traits are not clickable at all. see https://gtk-rs.org/gtk3-rs/git/docs/gtk/struct.Label.html#implements

the MiscExt is a gir issue though
