### ISSUE TITLE
gtk3-macros doctests are `compile_fail`

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk3-rs#468]
See https://github.com/gtk-rs/gtk-rs/pull/466#discussion_r615895426

Is this intentional? @bilelmoussaoui @BrainBlasted ?

**Comment by GuillaumeGomez** [comment]
If the problem is that the file isn't available, then we should either give a path which exist or mark those examples as `ignore` instead. Because currently, it sends tells readers that the code is invalid.

**Comment by sdroege** [comment]
Agreed, but maybe this can also be made to pass compilation at least (and have it `no_run`). I wanted to get this failure out of the way for now so someone who knows how this macro works in detail can solve it properly.

**Comment by GuillaumeGomez** [comment]
I think the problem is that the file specified doesn't exist, and that's check at compile time (otherwise, it would compile and the test would fail ;) ).

**Comment by bilelmoussaoui** [comment]
The struct in the example needs to implement ObjectImpl & WidgetImpl traits for it to compile

**Comment by GuillaumeGomez** [comment]
If it's "big implementation", you can hide those lines using `# ` at the start of the lines in the doc example.

**Comment by bilelmoussaoui** [comment]
they are not at all, it just needs someone having a look at it and sending a PR. Note we have the same issue on gtk4-rs as well.

**Comment by sdroege** [comment]
> The struct in the example needs to implement ObjectImpl & WidgetImpl traits for it to compile

That too in addition to the missing `.ui` file, yes
