### ISSUE TITLE
Sending a Notification does not work

### ISSUE THREAD

**Issue by floers** [gtk-rs/gtk3-rs#522]
I am working with gtk3-rs.

I am trying to send a Notification but it leads to the following error:
```
GLib-CRITICAL **: 07:20:11.245: g_variant_new_string: assertion 'string != NULL' failed
```

My code looks like this:

```
let notification = gio::Notification::new("Message");
notification.set_body(Some("body"));
app.send_notification(Some("message"), &notification);
```

Am I missing something or is this a bug?

**Comment by sdroege** [comment]
I can't reproduce this here. Can you provide a full testcase that reproduces it, for example around the `basics` example?

**Comment by floers** [comment]
Sure. I will do that later this day.

**Comment by floers** [comment]
I created this PR: https://github.com/gtk-rs/gtk-rs/pull/525 to show my problem but I cant reproduce the error with the example code. I guess I have different versions of everything in my project but I can only check that tomorrow.
Nevertheless code in the PR does not work... Am I missing something?

Is a PR like this ok? I didn't know how to share it otherwise.

**Comment by sdroege** [comment]
Yeah the equivalent C code also does not work for me, although lots of code I found does it exactly the same :)
No idea what's wrong there, maybe someone knowing this API can find the problem.

@bilelmoussaoui maybe?

```cpp
#include <gtk/gtk.h>

static void show_notification (GtkWidget *button, gpointer user_data) {
  GApplication *app = G_APPLICATION (user_data);
  GNotification *notification = g_notification_new ("title");

  g_application_send_notification (app, NULL, notification);
  g_object_unref (notification);

  return;
}

static void on_activate (GtkApplication *app) {
  GtkWidget *window = gtk_application_window_new (app);
  GtkWidget *button = gtk_button_new_with_label ("Hello, World!");
  g_signal_connect (button, "clicked", G_CALLBACK (show_notification), app);
  gtk_window_set_child (GTK_WINDOW (window), button);
  gtk_window_present (GTK_WINDOW (window));
}

int main (int argc, char *argv[]) {
  GtkApplication *app = gtk_application_new ("com.example.GtkApplication",
                                             G_APPLICATION_FLAGS_NONE);
  g_signal_connect (app, "activate", G_CALLBACK (on_activate), NULL);
  return g_application_run (G_APPLICATION (app), argc, argv);
}
```

**Comment by bilelmoussaoui** [comment]
GNotification expects you have a valid and installed desktop file installed that has the same name as the app-id used by your application, otherwise the notifications are just not sent.

**Comment by sdroege** [comment]
I see, is that documented somewhere? I missed the in the documentation at least :)

**Comment by bilelmoussaoui** [comment]
See https://developer.gnome.org/GNotification/. Mostly 
> If you don't have a desktop file whose base name matches the application id, then your notification will not show up.

**Comment by sdroege** [comment]
Sounds like something to add to the gio docs then. https://gitlab.gnome.org/GNOME/glib/-/issues/2405
