### ISSUE TITLE
GTK don't use the latest version of system-deps libary

### ISSUE THREAD

**Issue by qarmin** [gtk-rs/gtk3-rs#528]
Maybe I'm missing something but `system-deps` provide version 3.1.1 on crates.io https://crates.io/crates/system-deps

and GTK uses version 3.x
https://github.com/gtk-rs/gtk3-rs/blob/2f86e52185021b540913ae8e87cf857a1dbd1ea6/atk/sys/Cargo.toml#L1-L2

but in my and others apps I see that `system-deps` is pin to version "1.3.2" even  after executing `cargo update`

https://github.com/GuillaumeGomez/process-viewer/blob/e627a59c82451d425376b1a130e4d8d349528f63/Cargo.lock#L770-L771

https://github.com/qarmin/czkawka/blob/18ae283e8b86f202ae7c9881fb9854cee7f13410/Cargo.lock#L1930-L1931

**Comment by fengalin** [comment]
Your application uses `glib` v0.10.1, which [transitively depends on `system-deps` v1.3.x](https://crates.io/crates/glib-sys/0.10.1/dependencies).

`cargo update` should upgrade `system-deps` properly when you switch to the newest `gtk3-rs`, but it's not released yet.

**Comment by qarmin** [comment]
I completely forgot that Gtk-rs such rarely publich new version and I use old version

**Comment by fengalin** [comment]
> I completely forgot that Gtk-rs such rarely publich new version and I use old version

That's true! :) We are volunteers striving to provide a good `gtk` and other crates Rust experience, and it sometimes takes times before we reach something we deem appropriate for a release. Note that there will be a new release shortly with many many improvements and breaking changes. One thing which might help when upgrading is using the `get` prefix removal migration tools. See [this comment](https://github.com/gtk-rs/release/issues/137#issuecomment-824347893) for pointers.
