### ISSUE TITLE
Unable to hide window

### ISSUE THREAD

**Issue by samyak-jain** [gtk-rs/gtk3-rs#532]
I have a Gtk::Window object. However, I'm unable to hide the window. I tried calling the hide() method as well as the iconify() method as mentioned in the documentation: https://gtk-rs.org/docs/gtk/trait.GtkWindowExt.html but it didn't work. Am I missing something here? Please let me know if this isn't the right place to ask this.

**Comment by GuillaumeGomez** [comment]
It's indeed not the right place. Ask on https://discourse.gnome.org/. I'll create an issue to make it easier.

**Comment by bilelmoussaoui** [comment]
@GuillaumeGomez i have added this to gtk4-rs https://github.com/gtk-rs/gtk4-rs#useful-links maybe we can copy paste it for both core/gtk3 repositories?

**Comment by GuillaumeGomez** [comment]
That could be a nice add too. Still adding an issue template though. :)

**Comment by GuillaumeGomez** [comment]
I opened https://github.com/gtk-rs/gtk3-rs/pull/533. :)

**Comment by sdroege** [comment]
Was asked here: https://discourse.gnome.org/t/how-to-hide-a-window/6454
