### ISSUE TITLE
Need to check in subclassing code if GTK was initialized before and otherwise panic

### ISSUE THREAD

**Issue by sdroege** [gtk-rs/gtk3-rs#543]
See https://github.com/gtk-rs/gtk4-rs/issues/387

**Comment by sdroege** [comment]
@bilelmoussaoui You did this for gtk4-rs, can you backport this here?

**Comment by bilelmoussaoui** [comment]
definitely, this & #496 are two things i want to get fixed for this release

**Comment by sdroege** [comment]
@bilelmoussaoui Seems like we forgot this one
