### ISSUE TITLE
[HELP] How does one debug with gdb?

### ISSUE THREAD

**Issue by LoveIsGrief** [gtk-rs/gtk3-rs#544]
When debugging with `gdb`, it's not clear how to call functions of gtk objects.

Take this for example

https://github.com/gtk-rs/gtk3-rs/blob/8b57ba7e9fd082328c0d60f419c4fadd4c0594ec/examples/clock/main.rs#L19

Adding the line `println!("Time from label: {}", label.text().as_str());` below it works. However a breakpoint there with `gdb` fails to yield a string in the console

```
(gdb) print label.text().as_str()
Could not find function named 'gtk::auto::label::Label::text'
(gdb) print gtk::auto::label::LabelExt::text(label)
No symbol 'gtk::auto::label::LabelExt::text' in current context
```

Looking at `label` itself doesn't help either as I don't know how to call the functions I want from `inner` or `pointer`

```
(gdb) print label
$1 = gtk::auto::label::Label (glib::object::ObjectRef {inner: core::ptr::non_null::NonNull<gobject_sys::GObject> {pointer: 0x55555584f7f0}})
```

How do I use `gdb` with `gtk-rs`?

**Comment by sdroege** [comment]
That's a general Rust question, nothing really to do with gtk-rs or gtk. Can you ask that on https://users.rust-lang.org and link your question from here?

**Comment by LoveIsGrief** [comment]
You're right. I looked into it and it's a `rustc` issue https://github.com/rust-lang/rust/issues/1563 + https://github.com/rust-lang/rust/issues/33014 . [`gdb`](https://sourceware.org/bugzilla/show_bug.cgi?id=26202) has a corresponding bug.

Now I'm curious how debugging is done in rust...
