### ISSUE TITLE
[HELP] Why is gdk::Atom::value() unsafe

### ISSUE THREAD

**Issue by psychon** [gtk-rs/gtk3-rs#564]
As far as I can tell, this function just casts a number to another number.

https://github.com/gtk-rs/gtk3-rs/blob/69a49423a4164a2d1239af17279cf5154075007c/gdk/src/atom.rs#L47-L49

 I am not quite sure what `ffi::GdkAtom` actually is, but it seems to be an integer cast to a pointer (???): https://github.com/gtk-rs/gtk3-rs/blob/69a49423a4164a2d1239af17279cf5154075007c/gdk/src/atom.rs#L12

Thus, I would suggest to drop the `unsafe` from here: https://github.com/gtk-rs/gtk3-rs/blob/69a49423a4164a2d1239af17279cf5154075007c/gdk/src/atom.rs#L47

**Comment by bilelmoussaoui** [comment]
It probably shouldn't...the commit that added it doesn't mention the reasoning behind

**Comment by GuillaumeGomez** [comment]
It was apparently because of a clippy lint. Might be worth giving it another try if the situation changed.
