### ISSUE TITLE
Building an application using new API

### ISSUE THREAD

**Issue by tataDan** [gtk-rs/gtk3-rs#565]
I wrote an application named "nation_db" partially based on one of the applications in the "examples" directory.  I was able to successfully build and run it by doing the following:

After cloning the repository, I created a directory named "nation_db" in the "examples" directory of the "gtk3-rs-master" directory.

I added my "main.rs" file to the "nation_db" directory.

I added

```
[[bin]]
name = "nation_db"
path = "nation_db/main.rs"
```

to the "Cargo.toml" file in the "examples" directory.

I executed `cargo run --bin nation_db` and the application ran successfully.

I then created a new directory completely outside of the "gtk3-rs-master" directory, and moved my "main.rs" file to the "src" directory of that directory.

I found this at `https://gtk-rs.org/`.

```
Using latest, not published version

Include gtk in your Cargo.toml not as crate but from git:

[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk"
features = ["v3_16"]

```
So I added the following to my "Cargo.toml" file:

```
[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk-rs"
features = ["v3_16"]
```
I then executed `cargo run` and got the following error message:

```
daniel@delloptiplex780:~/RustPrograms/gtk-rs/nation_db$ cargo run
    Updating git repository `https://github.com/gtk-rs/gtk3-rs`
error: failed to select a version for `gtk`.
    ... required by package `nation_db v0.1.0 (/home/daniel/RustPrograms/gtk-rs/nation_db)`
versions that meet the requirements `*` are: 0.14.0

the package `nation_db` depends on `gtk`, with features: `v3_16` but `gtk` does not have these features.

failed to select a version for `gtk` which could resolve this conflict
```

My question is "Is it possible to build and run an application using the new API in this manner or should I wait for the new release to happen first?"  If it is possible, what would my "Cargo.toml" file look like?

**Comment by bilelmoussaoui** [comment]
```toml
[dependencies.gtk]
git = "https://github.com/gtk-rs/gtk3-rs"
```
is what you should use on your Cargo.toml till the next release is out. The information on the website is outdated and won't work for current git/future release(it will be updated before the release)

**Comment by tataDan** [comment]
Thanks for the extremely rapid response.  Your suggestion resolved the issue.

Omitting `features = ["v3_16"]` was the key to the resolution.

**Comment by bilelmoussaoui** [comment]
Yes, because we don't support 3.16 anymore, th minimum required version is 3.18. See https://gtk-rs.org/gtk3-rs/git/docs/gtk/#library-versions
