### ISSUE TITLE
[BUG] Regression after https://github.com/gtk-rs/gtk3-rs/pull/538

### ISSUE THREAD

**Issue by andy128k** [gtk-rs/gtk3-rs#568]
**Bug description**

Property `icon-size` of type `gtk::Image` has wrong type `IconSize` while it should be `i32`.

[gtk3](https://developer.gnome.org/gtk3/stable/GtkImage.html#GtkImage--icon-size)
[gtk4](https://developer.gnome.org/gtk4/stable/GtkImage.html#GtkImage--icon-size)

Creation panics like this:

```
Failed to create an instance of Image: BoolError { message: "property \'icon-size\' of type \'GtkImage\' can\'t be set from the given type (expected: \'gint\', got: \'GtkIconSize\')", filename: "/home/.../gtk-rs/gtk-rs-core/glib/src/object.rs", function: "glib::object", line: 2280 }
```

**Comment by sdroege** [comment]
CC @bilelmoussaoui

**Comment by bilelmoussaoui** [comment]
cc @GuillaumeGomez

**Comment by bilelmoussaoui** [comment]
Changing the gir file was a bad idea I guess :)

**Comment by sdroege** [comment]
Yes, you need to convert to the correct internal type when getting/setting the property now. This needs manual code.

**Comment by GuillaumeGomez** [comment]
We can have a field as manual?

**Comment by bilelmoussaoui** [comment]
a field how? for the builder pattern? not really

**Comment by GuillaumeGomez** [comment]
So it's always supposed to take an integer there, including in methods?

**Comment by bilelmoussaoui** [comment]
> So it's always supposed to take an integer there, including in methods?

Yes, is the enum actually used elsewhere ? If not, maybe we can just replace it's IntoGlib/StaticType implementations

**Comment by sdroege** [comment]
The public API should be the enum, and internally it needs to use integers for the properties.

**Comment by sdroege** [comment]
Manual code or a new gir feature, I guess
