### ISSUE TITLE
gdk-sys: test failed on fedora copr

### ISSUE THREAD

**Issue by ghost** [gtk-rs/gtk3-rs#597]
**Bug description**

---- cross_validate_constants_with_c stdout ----
Constant value mismatch for GDK_MICRO_VERSION
Rust: "23"
C:    "29"
thread 'cross_validate_constants_with_c' panicked at 'FAILED: 2734 passed; 1 failed', tests/abi.rs:107:13

https://download.copr.fedorainfracloud.org/results/remilauzier/gtk/fedora-rawhide-x86_64/02305839-rust-gdk-sys/builder-live.log.gz

**Comment by sdroege** [comment]
These version constants should be ignored in the `Gir.toml`. Do you want to submit a PR for that?

**Comment by bilelmoussaoui** [comment]
There is already an issue about this https://github.com/gtk-rs/gtk3-rs/issues/13
