### ISSUE TITLE
gtk-sys: test failed on fedora copr

### ISSUE THREAD

**Issue by ghost** [gtk-rs/gtk3-rs#598]
**Bug description**
https://download.copr.fedorainfracloud.org/results/remilauzier/gtk/fedora-rawhide-x86_64/02305848-rust-gtk-sys/builder-live.log.gz

tests/layout.c:244:61: error: 'GtkHeaderBarAccessible' undeclared (first use in this function); did you mean 'GtkLevelBarAccessible'?
  244 |     printf("%s;%zu;%zu\n", "GtkHeaderBarAccessible", sizeof(GtkHeaderBarAccessible), alignof(GtkHeaderBarAccessible));
      |                                                             ^~~~~~~~~~~~~~~~~~~~~~
      |                                                             GtkLevelBarAccessible
tests/layout.c:244:61: note: each undeclared identifier is reported only once for each function it appears in

**Comment by sdroege** [comment]
The corresponding header is not included by any GTK headers, so this fails (not just on Fedora copr). The header would have to be listed in the `.gir` file somehow so that it can be automatically included for the tests.

**Comment by sdroege** [comment]
I.e. this is a bug at the GTK level, not in the bindings.
