### ISSUE TITLE
gdk: Test failed on fedora copr

### ISSUE THREAD

**Issue by ghost** [gtk-rs/gtk3-rs#599]
**Bug description**
Unable to init server: Could not connect: Connection refused

(check_event-87e80c5b15526253:1069): Gdk-WARNING **: 06:20:30.328: cannot open display: 
     Running `/builddir/build/BUILD/gdk-0.14.0/target/release/deps/check_gir-a941f8d1019dffb5`

https://download.copr.fedorainfracloud.org/results/remilauzier/gtk/fedora-rawhide-x86_64/02305864-rust-gdk/builder-live.log.gz

**Comment by sdroege** [comment]
You need to have `xvfb` or some other X11 server running.

**Comment by bilelmoussaoui** [comment]
Closing as this is not related to the bindings themselves.
