### ISSUE TITLE
[HELP] How to setup development environment in macOS?

### ISSUE THREAD

**Issue by Jason5Lee** [gtk-rs/gtk3-rs#609]
I've executed [gtk-osx-setup.sh](https://gitlab.gnome.org/GNOME/gtk-osx/-/blob/master/gtk-osx-setup.sh) but `cargo check` still complaints about missing `gdk-3.0` .

I can't find any documentation about how to set up a development environment in macOS, please make one that could've saved my time.

**Comment by sdroege** [comment]
Did you configure `PKG_CONFIG_PATH` correctly so that `pkg-config` finds the GTK libraries? What's the output of `pkg-config --libs --cflags gtk+-3.0`?

**Comment by GuillaumeGomez** [comment]
Closing due to inactivi
ty.
