### ISSUE TITLE
[BUG] connect_clicked gets triggered when using set_active

### ISSUE THREAD

**Issue by GrbavaCigla** [gtk-rs/gtk3-rs#619]
**Bug description**

Callback to `connect_clicked` gets triggered on `set_active`.
I am trying to create custom notebook with `ToggleButton`s as tabs instead of traditional way. When I toggle one `ToggleButton`, I want all other `ToggleButton`s to turn off (I do that with `set_active`), but then `connect_clicked` callback gets triggered and causes recursive loop until all `ToggleButton`s are off.
Code:
https://github.com/GrbavaCigla/opendragui/blob/a3ff4ba9b635d745c7eccde7a4597326a9923ddf/src/notebook.rs#L38

**Comment by sdroege** [comment]
That's the expected behaviour. You'll have to inhibit the signals that you don't want to trigger, or maybe there's also another way. As this is more a support question, please ask on https://discourse.gnome.org. Thanks!
