### ISSUE TITLE
[HELP] How to figure out the state of fullscreen

### ISSUE THREAD

**Issue by ergpopler** [gtk-rs/gtk3-rs#623]
How do I figure out if the window is fullscreen or not? 
There are functions `fullscreen()` and `unfullscreen` but I can't find out how to get the status of whether the screen is or isn't fullscreen.
I am also using Webkit2gtk-rs, so I found [this](https://gtk-rs.org/webkit2gtk-rs/webkit2gtk/trait.WindowPropertiesExt.html#tymethod.get_fullscreen) but it doesn't seem to work.

**Comment by ergpopler** [comment]
I reckon I could compare the screen and window sizes, if they are the same I can be sure that it is in fullscreen. I cannot, however figure out how to detect when the window size has changed.

**Comment by sdroege** [comment]
Please ask for general support on the [GNOME discourse](https://discourse.gnome.org) or the gtk-rs [Matrix room](https://matrix.to/#/#rust:gnome.org).
