### ISSUE TITLE
Should `gdk::Event::is_pointer_emulated` really take a `&mut self`?

### ISSUE THREAD

**Issue by jneem** [gtk-rs/gtk3-rs#625]
The [`gdk::Event::is_pointer_emulated`](https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdk/struct.Event.html#method.is_pointer_emulated) method takes a `&mut self` argument, but it sounds like maybe it should take a `&self`? I'd be happy to send a PR if this is indeed the case.

**Comment by sdroege** [comment]
Yes it shouldn't take a mutable reference. If you send a PR, please also check if any other event getters have the same problem. Thanks!

**Comment by bilelmoussaoui** [comment]
Seems to be something wrong on either the introspection side of things or gir. See https://gitlab.gnome.org/World/Rust/libhandy-rs/-/issues/19

**Comment by jneem** [comment]
Hm, does that mean that I need to fix something in gir? Or is it ok just to modify `gdk/src/event.rs`?

**Comment by bilelmoussaoui** [comment]
> Hm, does that mean that I need to fix something in gir? Or is it ok just to modify `gdk/src/event.rs`?

It's fine to fix it on gdk's side for now, but i would open an issue to investigate it either on gir's side or here in gtk3

**Comment by sdroege** [comment]
How is gir relevant here? It's manually bound, so a simple human mistake in the code :)

**Comment by sdroege** [comment]
See https://github.com/gtk-rs/gtk3-rs/pull/626
