### ISSUE TITLE
[HELP] Unable to display a FileChooserNative dialog?

### ISSUE THREAD

**Issue by robmoss** [gtk-rs/gtk3-rs#631]
I'm experiencing an issue where I create a `FileChooserNative` dialog and call its `show()` method, but the dialog does not appear (even though `dialog.is_visible()` returns `true`). But I can create and display a regular `FileChooserDialog`. And, confusingly, if I replace `dialog.show()` with `dialog.run()`, the `FileChooserNative` dialog **does appear** (and block the main event loop). So I have no idea why `dialog.show()` doesn't appear to work for `FileChooserNative`. Is this a bug, or am I doing something wrong?

Here is a minimal working example that produces this behaviour on my computer (Debian Testing, gtk 3.24.30):

```
use gtk::{prelude::*, ResponseType};

fn main() {
    let application = gtk::Application::new(Some("test.file.chooser"), Default::default());
    application.connect_activate(build_ui);
    application.run();
}

fn build_ui(application: &gtk::Application) {
    let btn_normal = gtk::Button::builder().label("File Chooser").build();

    let btn_native = gtk::Button::builder().label("Native Chooser").build();

    let container = gtk::Box::new(gtk::Orientation::Vertical, 10);
    container.pack_start(&btn_normal, true, false, 0);
    container.pack_start(&btn_native, true, false, 0);

    let window = gtk::ApplicationWindow::builder()
        .application(application)
        .title("Test File Chooser")
        .child(&container)
        .build();

    let _window = window.clone();
    btn_native.connect_clicked(move |_| {
        let dlg = gtk::FileChooserNative::new(
            Some("Open a file"),
            Some(&_window),
            gtk::FileChooserAction::Open,
            Some("_Open"),
            Some("_Cancel"),
        );
        dlg.set_modal(true);
        // NOTE: replace the next line with `dlg.run()` and it does appear.
        dlg.show();
        println!("Native dialog visible: {}", dlg.is_visible());
        dlg.connect_response(|dlg, response| {
            println!("Response: {:#?}", response);
            dlg.hide();
        });
    });

    let _window = window.clone();
    btn_normal.connect_clicked(move |_| {
        let dlg = gtk::FileChooserDialog::with_buttons(
            Some("Open a file"),
            Some(&_window),
            gtk::FileChooserAction::Open,
            &[
                ("_Open", ResponseType::Accept),
                ("_Cancel", ResponseType::Cancel),
            ],
        );
        dlg.set_modal(true);
        dlg.show();
        println!("Normal dialog visible: {}", dlg.is_visible());
        dlg.connect_response(|dlg, response| {
            println!("Response: {:#?}", response);
            dlg.hide();
        });
    });

    window.show_all();
}
```

**Comment by sdroege** [comment]
>     btn_native.connect_clicked(move |_| {
>         let dlg = gtk::FileChooserNative::new(
>             Some("Open a file"),
>             Some(&_window),
>             gtk::FileChooserAction::Open,
>             Some("_Open"),
>             Some("_Cancel"),
>         );
>         dlg.set_modal(true);
>         // NOTE: replace the next line with `dlg.run()` and it does appear.
>         dlg.show();
>         println!("Native dialog visible: {}", dlg.is_visible());
>         dlg.connect_response(|dlg, response| {
>             println!("Response: {:#?}", response);
>             dlg.hide();
>         });
>     });

Your `dlg` is directly dropped at the end of the `connect_clicked` closure and because of that never appears on the screen. You have to keep it alive somewhere.

With normal widgets (like `FileChooserDialog`) this is not a problem because an additional reference is always owned by GTK until that dialog is destroyed/closed, but for native dialogs (which are not widgets) you have to keep them alive.

**Comment by robmoss** [comment]
Thank you very much, I completely missed that!
