### ISSUE TITLE
[BUG] Since pkg-config was added for build, it doesn't look anymore in current folder

### ISSUE THREAD

**Issue by GuillaumeGomez** [gtk-rs/gtk3-rs#666]
I precise the bug is on windows. Until now, I simply pasted the `.dll` files into my current directory (but I think it only matters for running the program, not building it) and then built it using `cargo build --release` and that was it. However, after I updated my gtk-rs version, it's not finding the libraries anymore...

I think the problem is on pkg-config but just in case, opening in here.

**Comment by sdroege** [comment]
This is expected behaviour. Finding GTK/etc libraries has to be done via pkg-config, not randomly from the current directory.
