### ISSUE TITLE
[gdk] Cannot create gdk::Geometry instance

### ISSUE THREAD

**Issue by wusyong** [gtk-rs/gtk3-rs#718]
Fields in gdk::Geometry become private.
This means we can't create the instance after 0.15
https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdk/struct.Geometry.html

**Comment by sdroege** [comment]
What's the use-case for creating a `gdk::Geometry` yourself exactly?

PR is in https://github.com/gtk-rs/gtk3-rs/pull/721

**Comment by bilelmoussaoui** [comment]
@sdroege see https://gtk-rs.org/gtk3-rs/stable/latest/docs/gdk/struct.Window.html#method.set_geometry_hints
