### ISSUE TITLE
the procedure entry point _divmoddi4 could not be located in the dynamic link library D:\msys32\mingw32\bin\libglib-2.0-0.dll

### ISSUE THREAD

**Issue by WillyAguilera1977** [gtk-rs/gtk3-rs#812]
hello
I have a problem when executing an application it tells me the above (in the title of the issue, in a dialogbox , and the application is terminated.

**Comment by sdroege** [comment]
That's a problem in your GLib build. Please report this to where you got it from, which is probably msys?
