### ISSUE TITLE
[HELP]  Why doesn't the merge PRs?

### ISSUE THREAD

**Issue by ski0090** [gtk-rs/gtk3-rs#852]
https://github.com/gtk-rs/gtk3-rs/pull/774
https://github.com/gtk-rs/gtk3-rs/pull/766

I have two PRs, but why doesn't the merge PRs?

**Comment by GuillaumeGomez** [comment]
Sorry didn't receive notifications for some reasons... Waiting for one update then everything will be merged. Closing in the meantime.
